# Generated by Django 3.0.7 on 2020-06-09 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Active'), (0, 'Passive'), (-1, 'Deleted')], default=1)),
                ('brand', models.CharField(max_length=255)),
                ('year', models.IntegerField()),
                ('model', models.CharField(max_length=255)),
                ('price', models.CharField(max_length=255)),
                ('mileage', models.CharField(max_length=255)),
                ('ext_color', models.CharField(max_length=255)),
                ('int_color', models.CharField(max_length=255)),
                ('transmission', models.CharField(max_length=255)),
                ('drivetrain', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
